name: Run Tests for Updated Workspaces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [app-a, app-b]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Changesets CLI
        run: yarn add -W @changesets/cli

      - name: Determine affected packages
        id: affected
        run: |
          npx -c "changeset status --since --json > affected.json"
          echo "affected=$(cat affected.json | jq -r '.packages[]')" >> $GITHUB_ENV

      - name: Install dependencies
        if: env.affected
        run: yarn install

      - name: Run tests for affected workspaces
        if: env.affected
        run: |
          echo "${{ env.affected }}" | tr ' ' '\n' | xargs -I {} bash -c 'cd packages/{} && yarn test'
